FROM golang:1.22-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest
RUN apk add --no-cache ffmpeg

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download
RUN go mod tidy

CMD air
