FROM golang:1.23-alpine as builder


WORKDIR /app

RUN go install github.com/air-verse/air@latest
RUN apk add --no-cache ffmpeg
RUN apk --no-cache add curl

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download
RUN go mod tidy

CMD air
